{{- /* https://www.chezmoi.io/user-guide/include-files-from-elsewhere/ */ -}}
{{- /* https://github.com/twpayne/chezmoi/discussions/3376 */ -}}

{{ if eq .osid "windows" }}
["AppData\\Local\\nvim"]
{{ else }}
[".config/nvim"]
{{ end }}
    type = "git-repo"
    url = "https://github.com/StephenGemin/nvim-starter"
    refreshPeriod = "720h"

{{ if eq .osid "windows" }}
[{{ joinPath (includeTemplate "get-catppuccin-themes-dir" .) "notepad_plus_plus" | quote }}]
    type = "git-repo"
    url = "https://github.com/catppuccin/notepad-plus-plus.git"
    refreshPeriod = "8766h"

[{{ joinPath .fontsDir "JetBrainsMono" | quote }}]
    type = "git-repo"
    url = "https://github.com/JetBrains/JetBrainsMono"
    clone.args = ["--depth", "1"]
    refreshPeriod = "8766h"
{{ end }}
