# https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#include-a-subdirectory-from-a-url

["AppData\\Local\\nvim"]
    type = "git-repo"
    url = "https://github.com/NvChad/starter"
    refreshPeriod = "720h"